add flag in photonID parameters
HEP-FCC/FCC-config pull request #175
Opened 2024-07-05 11:40 UTC by dasphy

Follow-up of https://github.com/HEP-FCC/k4RecCalorimeter/pull/79/ .
Added the flag in photon ID parameters, to calculate variables using log E weights instead of linear E weights.

Tagging @giovannimarchiori 

Cheers, Tong

2024-07-25 14:19 UTC, BrieucF requested changes
Hi Tong, thanks. The changes you propose break the config (see suggestion of modifications). For the next ones, can you please test that the code runs before to open the PR?

2024-07-25 14:19 UTC, BrieucF commented on FCCee/FullSim/ALLEGRO/ALLEGRO_o1_v03/run_digi_reco.py
> +                                                   do_widthTheta_logE_weights=logEWeightInPhotonID
```suggestion
                                                   do_widthTheta_logE_weights=logEWeightInPhotonID,
```

2024-07-25 14:19 UTC, BrieucF commented on FCCee/FullSim/ALLEGRO/ALLEGRO_o1_v03/run_digi_reco.py
> +                                                       do_widthTheta_logE_weights=logEWeightInPhotonID
```suggestion
                                                       do_widthTheta_logE_weights=logEWeightInPhotonID,
```

2024-07-26 05:20 UTC, dasphy commented
Oh yes thanks Brieuc, sorry for that. Modified.

2024-08-20 20:36 UTC, giovannimarchiori commented on FCCee/FullSim/ALLEGRO/ALLEGRO_o1_v03/run_digi_reco.py
> +logEWeightInPhotonID = False and runPhotonIDTool
Hi @dasphy ,
I don't think that the flag logEWeightInPhotonID should depend on runPhotonIDTool.
The runPhotonIDTool flag is used to decide whether we want to run the photon ID BDT and save its output score in the output ROOT file, while logEWeightInPhotonID is used to decide if we want to use logE or E weights when calculating some shape variables used to decorate the clusters, no matter whether we run or not the photon ID tool later. I would just set the flag to False

2024-08-29 07:42 UTC, giovannimarchiori approved these changes
Looks good now

2024-08-29 08:11 UTC, merged